name: Documentation

on:
  push:
    branches:
      - misc

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Cache dependencies
        uses: julia-actions/cache@v1

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl