name: "Run TODO to Issue"

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          AUTO_ASSIGN: "false"
          CLOSE_ISSUES: "true"

# see officiel documentation https://github.com/alstr/todo-to-issue-action